name: Deploy

on:
  # Trigger the workflow on push or pull request
  # but only for the main branch --
  push:
    branches:
      - master
  pull_request:
    types: [synchronize]
    branches:
      - master

    # Also trigger on page_build, as well as release created events
  page_build:
    release:
      types: # This configuration does not affect the page_build event above
        - created

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to cPanel
        id: deploy
        uses: pinkasey/cpanel-repository-action@v1.0.0
        with:
          hostname: https://cpanel.portalcatalao.com.br
          cpanel_token: ${{ secrets.CPANEL_TOKEN }}
          cpanel_username: portalcatalao
          repository_root: /home19/portalcatalao/address
          branch: master
      - name: echo deploy-duration
        run: echo "Deployment took ${{ steps.deploy.outputs.duration }} milliseconds"
